### ISSUE TITLE
Enable Github discussions

### ISSUE THREAD

**Issue by crass** [tink-crypto/tink#573]
**Help us help you**

None yet.

**Is your feature request related to a problem?**

Not with Tink itself.

**Describe the solution you'd like**

Enable Github discussions for the project.

**Describe alternatives you've considered**

Posting a question / request for help as an issue as many others have done.

**Additional context**

Enabling discussions could provide a kind of FAQ. Right now the issues seems to have a lot of questions that would be better off in the discussions. When an issue is closed its less likely that someone will find the information contained there.

**Comment by morambro** [comment]
We are going to archive this repo in this quarter as we split this repo into multiple more focused ones. We will consider enabling discussions in the new setting.

See https://github.com/tink-crypto/tink/issues/730
